#ifndef DUKICALCULATIONS_H
#define DUKICALCULATIONS_H

#include "dukicalculations_EXPORTS.h"  // automatically generated by cmake 
                                       // by the GENERATE_EXPORT_HEADER macro

float DUKICALCULATIONS_EXPORT pi_approx(int n);

#endif // DUKICALCULATIONS_H
