#ifndef SHARED_H__
#define SHARED_H__

#include "shared_EXPORTS.h"  // automatically generated by cmake 
                             // by the GENERATE_EXPORT_HEADER macro

void SHARED_EXPORT f();

#endif // SHARED_H__
