#ifndef SHARED_H__
#define SHARED_H__

#include "build/shared_EXPORTS.h"  // automatically generated by cmake 
                             // by the GENERATE_EXPORT_HEADER macro

void SHARED_EXPORT f();

float SHARED_EXPORT pi_approx(int n);

#endif // SHARED_H__
